
logo: "/images/Perivier_headshot.jpg?raw=true" # your photo (or logo) here
title: Noemie Perivier # your name (or website title) here
description: PhD candidate in Operations research
<br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
