
logo: "/images/Perivier_headshot.jpg?raw=true" # your photo (or logo) here
title: Noemie Perivier # your name (or website title) here
description: >
  PhD candidate in Operations research
  <i>Columbia University</i>
  
theme: jekyll-theme-minimal
